/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedContactosRouteImport } from './routes/_authenticated/contactos'
import { Route as AuthenticatedPanelRouteImport } from './routes/_authenticated/panel'
import { Route as AuthenticatedSolicitudesRouteImport } from './routes/_authenticated/solicitudes'
import { Route as AuthenticatedVendedoresRouteImport } from './routes/_authenticated/vendedores'
import { Route as AuthenticatedSolicitudIdRouteImport } from './routes/_authenticated/solicitud.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedContactosRoute = AuthenticatedContactosRouteImport.update({
  id: '/contactos',
  path: '/contactos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPanelRoute = AuthenticatedPanelRouteImport.update({
  id: '/panel',
  path: '/panel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSolicitudesRoute =
  AuthenticatedSolicitudesRouteImport.update({
    id: '/solicitudes',
    path: '/solicitudes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVendedoresRoute = AuthenticatedVendedoresRouteImport.update({
  id: '/vendedores',
  path: '/vendedores',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSolicitudIdRoute =
  AuthenticatedSolicitudIdRouteImport.update({
    id: '/solicitud/$id',
    path: '/solicitud/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contactos': typeof AuthenticatedContactosRoute
  '/panel': typeof AuthenticatedPanelRoute
  '/solicitudes': typeof AuthenticatedSolicitudesRoute
  '/vendedores': typeof AuthenticatedVendedoresRoute
  '/solicitud/$id': typeof AuthenticatedSolicitudIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contactos': typeof AuthenticatedContactosRoute
  '/panel': typeof AuthenticatedPanelRoute
  '/solicitudes': typeof AuthenticatedSolicitudesRoute
  '/vendedores': typeof AuthenticatedVendedoresRoute
  '/solicitud/$id': typeof AuthenticatedSolicitudIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/contactos': typeof AuthenticatedContactosRoute
  '/_authenticated/panel': typeof AuthenticatedPanelRoute
  '/_authenticated/solicitudes': typeof AuthenticatedSolicitudesRoute
  '/_authenticated/vendedores': typeof AuthenticatedVendedoresRoute
  '/_authenticated/solicitud/$id': typeof AuthenticatedSolicitudIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/contactos'
    | '/panel'
    | '/solicitudes'
    | '/vendedores'
    | '/solicitud/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/contactos'
    | '/panel'
    | '/solicitudes'
    | '/vendedores'
    | '/solicitud/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/contactos'
    | '/_authenticated/panel'
    | '/_authenticated/solicitudes'
    | '/_authenticated/vendedores'
    | '/_authenticated/solicitud/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/contactos': {
      id: '/_authenticated/contactos'
      path: '/contactos'
      fullPath: '/contactos'
      preLoaderRoute: typeof AuthenticatedContactosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/panel': {
      id: '/_authenticated/panel'
      path: '/panel'
      fullPath: '/panel'
      preLoaderRoute: typeof AuthenticatedPanelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/solicitudes': {
      id: '/_authenticated/solicitudes'
      path: '/solicitudes'
      fullPath: '/solicitudes'
      preLoaderRoute: typeof AuthenticatedSolicitudesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vendedores': {
      id: '/_authenticated/vendedores'
      path: '/vendedores'
      fullPath: '/vendedores'
      preLoaderRoute: typeof AuthenticatedVendedoresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/solicitud/$id': {
      id: '/_authenticated/solicitud/$id'
      path: '/solicitud/$id'
      fullPath: '/solicitud/$id'
      preLoaderRoute: typeof AuthenticatedSolicitudIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedContactosRoute: typeof AuthenticatedContactosRoute
  AuthenticatedPanelRoute: typeof AuthenticatedPanelRoute
  AuthenticatedSolicitudesRoute: typeof AuthenticatedSolicitudesRoute
  AuthenticatedVendedoresRoute: typeof AuthenticatedVendedoresRoute
  AuthenticatedSolicitudIdRoute: typeof AuthenticatedSolicitudIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedContactosRoute: AuthenticatedContactosRoute,
  AuthenticatedPanelRoute: AuthenticatedPanelRoute,
  AuthenticatedSolicitudesRoute: AuthenticatedSolicitudesRoute,
  AuthenticatedVendedoresRoute: AuthenticatedVendedoresRoute,
  AuthenticatedSolicitudIdRoute: AuthenticatedSolicitudIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
