/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedCampanasRouteImport } from './routes/_authenticated/campanas'
import { Route as AuthenticatedConfiguracionRouteImport } from './routes/_authenticated/configuracion'
import { Route as AuthenticatedContactosRouteImport } from './routes/_authenticated/contactos'
import { Route as AuthenticatedExportarRouteImport } from './routes/_authenticated/exportar'
import { Route as AuthenticatedPanelRouteImport } from './routes/_authenticated/panel'
import { Route as AuthenticatedPlantillasRouteImport } from './routes/_authenticated/plantillas'
import { Route as AuthenticatedPreguntasRouteImport } from './routes/_authenticated/preguntas'
import { Route as AuthenticatedSolicitudesRouteImport } from './routes/_authenticated/solicitudes'
import { Route as AuthenticatedUsuariosRouteImport } from './routes/_authenticated/usuarios'
import { Route as AuthenticatedVendedoresRouteImport } from './routes/_authenticated/vendedores'
import { Route as AuthenticatedSolicitudIdRouteImport } from './routes/_authenticated/solicitud.$id'
import { Route as ApiCronBotRouteImport } from './routes/api/cron/bot'
import { Route as ApiWhatsappWebhookRouteImport } from './routes/api/whatsapp/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCampanasRoute = AuthenticatedCampanasRouteImport.update({
  id: '/campanas',
  path: '/campanas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracionRoute =
  AuthenticatedConfiguracionRouteImport.update({
    id: '/configuracion',
    path: '/configuracion',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContactosRoute = AuthenticatedContactosRouteImport.update({
  id: '/contactos',
  path: '/contactos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExportarRoute = AuthenticatedExportarRouteImport.update({
  id: '/exportar',
  path: '/exportar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPanelRoute = AuthenticatedPanelRouteImport.update({
  id: '/panel',
  path: '/panel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlantillasRoute = AuthenticatedPlantillasRouteImport.update({
  id: '/plantillas',
  path: '/plantillas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPreguntasRoute = AuthenticatedPreguntasRouteImport.update({
  id: '/preguntas',
  path: '/preguntas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSolicitudesRoute =
  AuthenticatedSolicitudesRouteImport.update({
    id: '/solicitudes',
    path: '/solicitudes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsuariosRoute = AuthenticatedUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVendedoresRoute = AuthenticatedVendedoresRouteImport.update({
  id: '/vendedores',
  path: '/vendedores',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSolicitudIdRoute =
  AuthenticatedSolicitudIdRouteImport.update({
    id: '/solicitud/$id',
    path: '/solicitud/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiCronBotRoute = ApiCronBotRouteImport.update({
  id: '/api/cron/bot',
  path: '/api/cron/bot',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWhatsappWebhookRoute = ApiWhatsappWebhookRouteImport.update({
  id: '/api/whatsapp/webhook',
  path: '/api/whatsapp/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/campanas': typeof AuthenticatedCampanasRoute
  '/configuracion': typeof AuthenticatedConfiguracionRoute
  '/contactos': typeof AuthenticatedContactosRoute
  '/exportar': typeof AuthenticatedExportarRoute
  '/panel': typeof AuthenticatedPanelRoute
  '/plantillas': typeof AuthenticatedPlantillasRoute
  '/preguntas': typeof AuthenticatedPreguntasRoute
  '/solicitudes': typeof AuthenticatedSolicitudesRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/vendedores': typeof AuthenticatedVendedoresRoute
  '/solicitud/$id': typeof AuthenticatedSolicitudIdRoute
  '/api/cron/bot': typeof ApiCronBotRoute
  '/api/whatsapp/webhook': typeof ApiWhatsappWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/campanas': typeof AuthenticatedCampanasRoute
  '/configuracion': typeof AuthenticatedConfiguracionRoute
  '/contactos': typeof AuthenticatedContactosRoute
  '/exportar': typeof AuthenticatedExportarRoute
  '/panel': typeof AuthenticatedPanelRoute
  '/plantillas': typeof AuthenticatedPlantillasRoute
  '/preguntas': typeof AuthenticatedPreguntasRoute
  '/solicitudes': typeof AuthenticatedSolicitudesRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/vendedores': typeof AuthenticatedVendedoresRoute
  '/solicitud/$id': typeof AuthenticatedSolicitudIdRoute
  '/api/cron/bot': typeof ApiCronBotRoute
  '/api/whatsapp/webhook': typeof ApiWhatsappWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/campanas': typeof AuthenticatedCampanasRoute
  '/_authenticated/configuracion': typeof AuthenticatedConfiguracionRoute
  '/_authenticated/contactos': typeof AuthenticatedContactosRoute
  '/_authenticated/exportar': typeof AuthenticatedExportarRoute
  '/_authenticated/panel': typeof AuthenticatedPanelRoute
  '/_authenticated/plantillas': typeof AuthenticatedPlantillasRoute
  '/_authenticated/preguntas': typeof AuthenticatedPreguntasRoute
  '/_authenticated/solicitudes': typeof AuthenticatedSolicitudesRoute
  '/_authenticated/usuarios': typeof AuthenticatedUsuariosRoute
  '/_authenticated/vendedores': typeof AuthenticatedVendedoresRoute
  '/_authenticated/solicitud/$id': typeof AuthenticatedSolicitudIdRoute
  '/api/cron/bot': typeof ApiCronBotRoute
  '/api/whatsapp/webhook': typeof ApiWhatsappWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/campanas'
    | '/configuracion'
    | '/contactos'
    | '/exportar'
    | '/panel'
    | '/plantillas'
    | '/preguntas'
    | '/solicitudes'
    | '/usuarios'
    | '/vendedores'
    | '/solicitud/$id'
    | '/api/cron/bot'
    | '/api/whatsapp/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/campanas'
    | '/configuracion'
    | '/contactos'
    | '/exportar'
    | '/panel'
    | '/plantillas'
    | '/preguntas'
    | '/solicitudes'
    | '/usuarios'
    | '/vendedores'
    | '/solicitud/$id'
    | '/api/cron/bot'
    | '/api/whatsapp/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/campanas'
    | '/_authenticated/configuracion'
    | '/_authenticated/contactos'
    | '/_authenticated/exportar'
    | '/_authenticated/panel'
    | '/_authenticated/plantillas'
    | '/_authenticated/preguntas'
    | '/_authenticated/solicitudes'
    | '/_authenticated/usuarios'
    | '/_authenticated/vendedores'
    | '/_authenticated/solicitud/$id'
    | '/api/cron/bot'
    | '/api/whatsapp/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiCronBotRoute: typeof ApiCronBotRoute
  ApiWhatsappWebhookRoute: typeof ApiWhatsappWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/campanas': {
      id: '/_authenticated/campanas'
      path: '/campanas'
      fullPath: '/campanas'
      preLoaderRoute: typeof AuthenticatedCampanasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracion': {
      id: '/_authenticated/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof AuthenticatedConfiguracionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contactos': {
      id: '/_authenticated/contactos'
      path: '/contactos'
      fullPath: '/contactos'
      preLoaderRoute: typeof AuthenticatedContactosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/exportar': {
      id: '/_authenticated/exportar'
      path: '/exportar'
      fullPath: '/exportar'
      preLoaderRoute: typeof AuthenticatedExportarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/panel': {
      id: '/_authenticated/panel'
      path: '/panel'
      fullPath: '/panel'
      preLoaderRoute: typeof AuthenticatedPanelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/plantillas': {
      id: '/_authenticated/plantillas'
      path: '/plantillas'
      fullPath: '/plantillas'
      preLoaderRoute: typeof AuthenticatedPlantillasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/preguntas': {
      id: '/_authenticated/preguntas'
      path: '/preguntas'
      fullPath: '/preguntas'
      preLoaderRoute: typeof AuthenticatedPreguntasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/solicitudes': {
      id: '/_authenticated/solicitudes'
      path: '/solicitudes'
      fullPath: '/solicitudes'
      preLoaderRoute: typeof AuthenticatedSolicitudesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/usuarios': {
      id: '/_authenticated/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AuthenticatedUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vendedores': {
      id: '/_authenticated/vendedores'
      path: '/vendedores'
      fullPath: '/vendedores'
      preLoaderRoute: typeof AuthenticatedVendedoresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/solicitud/$id': {
      id: '/_authenticated/solicitud/$id'
      path: '/solicitud/$id'
      fullPath: '/solicitud/$id'
      preLoaderRoute: typeof AuthenticatedSolicitudIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/cron/bot': {
      id: '/api/cron/bot'
      path: '/api/cron/bot'
      fullPath: '/api/cron/bot'
      preLoaderRoute: typeof ApiCronBotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/whatsapp/webhook': {
      id: '/api/whatsapp/webhook'
      path: '/api/whatsapp/webhook'
      fullPath: '/api/whatsapp/webhook'
      preLoaderRoute: typeof ApiWhatsappWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCampanasRoute: typeof AuthenticatedCampanasRoute
  AuthenticatedConfiguracionRoute: typeof AuthenticatedConfiguracionRoute
  AuthenticatedContactosRoute: typeof AuthenticatedContactosRoute
  AuthenticatedExportarRoute: typeof AuthenticatedExportarRoute
  AuthenticatedPanelRoute: typeof AuthenticatedPanelRoute
  AuthenticatedPlantillasRoute: typeof AuthenticatedPlantillasRoute
  AuthenticatedPreguntasRoute: typeof AuthenticatedPreguntasRoute
  AuthenticatedSolicitudesRoute: typeof AuthenticatedSolicitudesRoute
  AuthenticatedUsuariosRoute: typeof AuthenticatedUsuariosRoute
  AuthenticatedVendedoresRoute: typeof AuthenticatedVendedoresRoute
  AuthenticatedSolicitudIdRoute: typeof AuthenticatedSolicitudIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCampanasRoute: AuthenticatedCampanasRoute,
  AuthenticatedConfiguracionRoute: AuthenticatedConfiguracionRoute,
  AuthenticatedContactosRoute: AuthenticatedContactosRoute,
  AuthenticatedExportarRoute: AuthenticatedExportarRoute,
  AuthenticatedPanelRoute: AuthenticatedPanelRoute,
  AuthenticatedPlantillasRoute: AuthenticatedPlantillasRoute,
  AuthenticatedPreguntasRoute: AuthenticatedPreguntasRoute,
  AuthenticatedSolicitudesRoute: AuthenticatedSolicitudesRoute,
  AuthenticatedUsuariosRoute: AuthenticatedUsuariosRoute,
  AuthenticatedVendedoresRoute: AuthenticatedVendedoresRoute,
  AuthenticatedSolicitudIdRoute: AuthenticatedSolicitudIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiCronBotRoute: ApiCronBotRoute,
  ApiWhatsappWebhookRoute: ApiWhatsappWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
